spring.application.name=Smart Store

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USERNAME}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000 
jwt.refresh.expiration=2592000000 

# MongoDB connection pool settings
spring.data.mongodb.connection-pool.max-size=50
spring.data.mongodb.connection-pool.min-size=5
spring.data.mongodb.connection-pool.max-wait-time=1000
spring.data.mongodb.connection-pool.max-connection-idle-time=60000
spring.data.mongodb.connection-pool.max-connection-life-time=120000

