package com.raghunath.smartstore.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Document(collection = "users")
public class User {
    @Id
    private String id;

    private String fullName;
    private String mobileNumber;
    private String email;
    private String password;

    // Auditing fields
    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;

    // Security fields
    private boolean isActive = true;
    private int failedLoginAttempts = 0;
    private LocalDateTime lastFailedLoginAt;
    private LocalDateTime lastLoginAt;
    private LocalDateTime passwordUpdatedAt;
    private LocalDateTime globalLogoutAt;

    // Getters and setters automatically generated by @Data
}
